version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    restart: always
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password
#      POSTGRES_DB: postgres
  server:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
    restart: always

    ports:
      - "8081:8081"
    volumes:
      - ./postgres.yml:/src/config.yml:r