version: "3.8"

services:
  postgres_db:
    container_name: core_pg_db
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${database.username}
      - POSTGRES_USER=mamun
      - POSTGRES_PASSWORD=123

    restart: always
    networks:
      - servernet

  server:
    container_name: go_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    links:
      - postgres_db:postgres_db
    restart: on-failure
    networks:
      - servernet



# networks to be created to communication between containers
networks:
  servernet:
    driver: bridge
