version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    restart: on-failure
    networks:
      - servernet

  postgres:
    container_name: pg_db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: mamun
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_pg_go
    restart: always
    networks:
      - servernet


# networks to be created to communication between containers
networks:
  servernet:
    driver: bridge
